import type { Config } from "tailwindcss";

export default {
  darkMode: ["class"],
  content: ["./pages/**/*.{ts,tsx}", "./components/**/*.{ts,tsx}", "./app/**/*.{ts,tsx}", "./src/**/*.{ts,tsx}"],
  prefix: "",
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        border: "hsl(var(--border))",
        "border-subtle": "hsl(var(--border-subtle))",
        "border-strong": "hsl(var(--border-strong))",
        input: "hsl(var(--input))",
        "input-focus": "hsl(var(--input-focus))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        "background-subtle": "hsl(var(--background-subtle))",
        "background-muted": "hsl(var(--background-muted))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
          hover: "hsl(var(--primary-hover))",
          active: "hsl(var(--primary-active))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
          hover: "hsl(var(--secondary-hover))",
          active: "hsl(var(--secondary-active))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
          hover: "hsl(var(--destructive-hover))",
          muted: "hsl(var(--destructive-muted))",
        },
        success: {
          DEFAULT: "hsl(var(--success))",
          foreground: "hsl(var(--success-foreground))",
          hover: "hsl(var(--success-hover))",
          muted: "hsl(var(--success-muted))",
        },
        warning: {
          DEFAULT: "hsl(var(--warning))",
          foreground: "hsl(var(--warning-foreground))",
          hover: "hsl(var(--warning-hover))",
          muted: "hsl(var(--warning-muted))",
        },
        info: {
          DEFAULT: "hsl(var(--info))",
          foreground: "hsl(var(--info-foreground))",
          hover: "hsl(var(--info-hover))",
          muted: "hsl(var(--info-muted))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
          hover: "hsl(var(--muted-hover))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
          hover: "hsl(var(--accent-hover))",
          active: "hsl(var(--accent-active))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
          elevated: "hsl(var(--card-elevated))",
          sunken: "hsl(var(--card-sunken))",
        },
        sidebar: {
          DEFAULT: "hsl(var(--sidebar-background))",
          foreground: "hsl(var(--sidebar-foreground))",
          primary: "hsl(var(--sidebar-primary))",
          "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
          accent: "hsl(var(--sidebar-accent))",
          "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
          border: "hsl(var(--sidebar-border))",
          ring: "hsl(var(--sidebar-ring))",
        },
        // Silver Metallic Scale
        silver: {
          50: "hsl(var(--silver-50))",
          100: "hsl(var(--silver-100))",
          200: "hsl(var(--silver-200))",
          300: "hsl(var(--silver-300))",
          400: "hsl(var(--silver-400))",
          500: "hsl(var(--silver-500))",
          600: "hsl(var(--silver-600))",
          700: "hsl(var(--silver-700))",
          800: "hsl(var(--silver-800))",
          900: "hsl(var(--silver-900))",
          950: "hsl(var(--silver-950))",
        },
        // Chart Colors
        chart: {
          1: "hsl(var(--chart-1))",
          2: "hsl(var(--chart-2))",
          3: "hsl(var(--chart-3))",
          4: "hsl(var(--chart-4))",
          5: "hsl(var(--chart-5))",
          6: "hsl(var(--chart-6))",
          "accent-1": "hsl(var(--chart-accent-1))",
          "accent-2": "hsl(var(--chart-accent-2))",
          "accent-3": "hsl(var(--chart-accent-3))",
          "accent-4": "hsl(var(--chart-accent-4))",
          "accent-5": "hsl(var(--chart-accent-5))",
        },
        // Skeleton
        skeleton: {
          DEFAULT: "hsl(var(--skeleton))",
          foreground: "hsl(var(--skeleton-foreground))",
        },
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      fontFamily: {
        sans: ["Inter", "ui-sans-serif", "system-ui", "sans-serif"],
        display: ["Space Grotesk", "ui-sans-serif", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      fontSize: {
        // Headline Scale
        "h1": ["var(--text-h1)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tight)", fontWeight: "var(--font-bold)" }],
        "h2": ["var(--text-h2)", { lineHeight: "var(--leading-tight)", letterSpacing: "var(--tracking-tight)", fontWeight: "var(--font-bold)" }],
        "h3": ["var(--text-h3)", { lineHeight: "var(--leading-snug)", letterSpacing: "var(--tracking-normal)", fontWeight: "var(--font-semibold)" }],
        "h4": ["var(--text-h4)", { lineHeight: "var(--leading-snug)", letterSpacing: "var(--tracking-normal)", fontWeight: "var(--font-semibold)" }],
        "h5": ["var(--text-h5)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)", fontWeight: "var(--font-medium)" }],
        "h6": ["var(--text-h6)", { lineHeight: "var(--leading-normal)", letterSpacing: "var(--tracking-normal)", fontWeight: "var(--font-medium)" }],
        // Body Text Scale
        "body-lg": ["var(--text-body-lg)", { lineHeight: "var(--leading-relaxed)" }],
        "body": ["var(--text-body)", { lineHeight: "var(--leading-normal)" }],
        "body-sm": ["var(--text-body-sm)", { lineHeight: "var(--leading-normal)" }],
        "body-xs": ["var(--text-body-xs)", { lineHeight: "var(--leading-normal)" }],
        // Monospace Scale
        "mono-lg": ["var(--text-mono-lg)", { lineHeight: "var(--leading-normal)", fontFamily: "var(--font-mono)" }],
        "mono": ["var(--text-mono)", { lineHeight: "var(--leading-normal)", fontFamily: "var(--font-mono)" }],
        "mono-sm": ["var(--text-mono-sm)", { lineHeight: "var(--leading-normal)", fontFamily: "var(--font-mono)" }],
        "mono-xs": ["var(--text-mono-xs)", { lineHeight: "var(--leading-tight)", fontFamily: "var(--font-mono)" }],
      },
      lineHeight: {
        none: "var(--leading-none)",
        tight: "var(--leading-tight)",
        snug: "var(--leading-snug)",
        normal: "var(--leading-normal)",
        relaxed: "var(--leading-relaxed)",
        loose: "var(--leading-loose)",
      },
      letterSpacing: {
        tighter: "var(--tracking-tighter)",
        tight: "var(--tracking-tight)",
        normal: "var(--tracking-normal)",
        wide: "var(--tracking-wide)",
        wider: "var(--tracking-wider)",
        widest: "var(--tracking-widest)",
      },
      fontWeight: {
        light: "var(--font-light)",
        normal: "var(--font-normal)",
        medium: "var(--font-medium)",
        semibold: "var(--font-semibold)",
        bold: "var(--font-bold)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
        "fade-in": {
          from: { opacity: "0" },
          to: { opacity: "1" },
        },
        "fade-out": {
          from: { opacity: "1" },
          to: { opacity: "0" },
        },
        "fade-up": {
          from: { opacity: "0", transform: "translateY(20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-down": {
          from: { opacity: "0", transform: "translateY(-20px)" },
          to: { opacity: "1", transform: "translateY(0)" },
        },
        "fade-left": {
          from: { opacity: "0", transform: "translateX(20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "fade-right": {
          from: { opacity: "0", transform: "translateX(-20px)" },
          to: { opacity: "1", transform: "translateX(0)" },
        },
        "slide-in-right": {
          from: { transform: "translateX(100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-in-left": {
          from: { transform: "translateX(-100%)" },
          to: { transform: "translateX(0)" },
        },
        "slide-in-up": {
          from: { transform: "translateY(100%)" },
          to: { transform: "translateY(0)" },
        },
        "slide-in-down": {
          from: { transform: "translateY(-100%)" },
          to: { transform: "translateY(0)" },
        },
        "scale-in": {
          from: { opacity: "0", transform: "scale(0.95)" },
          to: { opacity: "1", transform: "scale(1)" },
        },
        "scale-out": {
          from: { opacity: "1", transform: "scale(1)" },
          to: { opacity: "0", transform: "scale(0.95)" },
        },
        "rotate-in": {
          from: { opacity: "0", transform: "rotate(-10deg) scale(0.95)" },
          to: { opacity: "1", transform: "rotate(0) scale(1)" },
        },
        "flip-in": {
          from: { opacity: "0", transform: "perspective(400px) rotateY(90deg)" },
          to: { opacity: "1", transform: "perspective(400px) rotateY(0)" },
        },
        shimmer: {
          from: { backgroundPosition: "200% 0" },
          to: { backgroundPosition: "-200% 0" },
        },
        pulse: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.8" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
        "float-slow": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-5px)" },
        },
        bounce: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-25%)" },
        },
        wiggle: {
          "0%, 100%": { transform: "rotate(-3deg)" },
          "50%": { transform: "rotate(3deg)" },
        },
        spin: {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "spin-slow": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        glow: {
          "0%, 100%": { boxShadow: "var(--shadow-glow)" },
          "50%": { boxShadow: "var(--shadow-glow-strong)" },
        },
        "text-shimmer": {
          from: { backgroundPosition: "0 0" },
          to: { backgroundPosition: "-200% 0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
        "fade-in": "fade-in 0.5s ease-out",
        "fade-out": "fade-out 0.5s ease-out",
        "fade-up": "fade-up 0.5s ease-out",
        "fade-down": "fade-down 0.5s ease-out",
        "fade-left": "fade-left 0.5s ease-out",
        "fade-right": "fade-right 0.5s ease-out",
        "slide-in-right": "slide-in-right 0.3s ease-out",
        "slide-in-left": "slide-in-left 0.3s ease-out",
        "slide-in-up": "slide-in-up 0.3s ease-out",
        "slide-in-down": "slide-in-down 0.3s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "scale-out": "scale-out 0.3s ease-out",
        "rotate-in": "rotate-in 0.4s ease-out",
        "flip-in": "flip-in 0.5s ease-out",
        shimmer: "shimmer 2s linear infinite",
        pulse: "pulse 2s ease-in-out infinite",
        "pulse-soft": "pulse-soft 2s ease-in-out infinite",
        float: "float 3s ease-in-out infinite",
        "float-slow": "float-slow 4s ease-in-out infinite",
        bounce: "bounce 1s infinite",
        wiggle: "wiggle 1s ease-in-out infinite",
        spin: "spin 1s linear infinite",
        "spin-slow": "spin-slow 3s linear infinite",
        glow: "glow 2s ease-in-out infinite",
        "text-shimmer": "text-shimmer 3s linear infinite",
      },
      backgroundImage: {
        "gradient-silver": "var(--gradient-silver)",
        "gradient-silver-reverse": "var(--gradient-silver-reverse)",
        "gradient-metallic": "var(--gradient-metallic)",
        "gradient-metallic-horizontal": "var(--gradient-metallic-horizontal)",
        "gradient-dark": "var(--gradient-dark)",
        "gradient-dark-reverse": "var(--gradient-dark-reverse)",
        "gradient-glass": "var(--gradient-glass)",
        "gradient-glass-subtle": "var(--gradient-glass-subtle)",
        "gradient-radial-silver": "var(--gradient-radial-silver)",
        "gradient-radial-shine": "var(--gradient-radial-shine)",
        "gradient-radial-spotlight": "var(--gradient-radial-spotlight)",
        "gradient-conic-silver": "var(--gradient-conic-silver)",
        "skeleton-shimmer": "var(--skeleton-shimmer)",
        "grid-pattern": "linear-gradient(hsl(var(--border)) 1px, transparent 1px), linear-gradient(90deg, hsl(var(--border)) 1px, transparent 1px)",
      },
      boxShadow: {
        soft: "var(--shadow-soft)",
        medium: "var(--shadow-medium)",
        strong: "var(--shadow-strong)",
        heavy: "var(--shadow-heavy)",
        glow: "var(--shadow-glow)",
        "glow-strong": "var(--shadow-glow-strong)",
        neon: "var(--shadow-neon)",
        "neon-subtle": "var(--shadow-neon-subtle)",
        inner: "var(--shadow-inner)",
        "inner-strong": "var(--shadow-inner-strong)",
        success: "var(--shadow-success)",
        warning: "var(--shadow-warning)",
        destructive: "var(--shadow-destructive)",
        info: "var(--shadow-info)",
      },
      spacing: {
        page: "var(--spacing-page)",
        section: "var(--spacing-section)",
        card: "var(--spacing-card)",
      },
      maxWidth: {
        content: "var(--max-width-content)",
        narrow: "var(--max-width-narrow)",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
} satisfies Config;
